---
JoinBroadcast1: §7=======================
LEER: " "
JoinBroadcast2: ' §8» §6Welcome Back to §l§4XFire§2Games!!'
JoinBroadcast3: ' §8» §dOwner AloofXFire777§7'
JoinBroadcast4: ' §8» §fAre You Ready§7'
LEER2: " "
JoinBroadcast5: §7=======================
BlockBreakMessage: ' §cError!'
Hub/Lobby: ' §c Welcome To §l§4XFire§2GamesHub!'
JoinTitle: ' §7[§a»§7] §aWelcome!'
Prefix: §7[§6§lLOBBY§r§7]
Chat: ' §7Error!'
...
